### PR TITLE
`Upper` and `Lower` string expressions

### PR DESCRIPTION
**Pull request by gdebrauwer**
2 simple expressions to make text uppercase or lowercase
```php
use Tpetry\QueryExpressions\Function\String\Lower;
use Tpetry\QueryExpressions\Function\String\Upper;

new Lower('foo');
new Upper('bar');
```

### CODE REVIEW

**Comment by tpetry** [comment]
Can you enhance it by an optional 2. parameter provodong a collation that should be used at the column?

Like this `new Lower('somecolumn', 'utf8mb4_general_ci')` which translates to `lower(convert('somecolumn' USING utf8mb4))`. But needs specific implementations for each dbms.

**Comment by gdebrauwer** [comment]
There does not seem to be a collation name that is the same in each dbms. So I'm not sure what the best setup is in the tests, in order provide a different expression for each dbms to be executed 🤔

**Comment by gdebrauwer** [comment]
You should have write access

Screen Shot 2023-08-31 at 19 01 26

**Comment by tpetry** [comment]
I still was not able to push my changes for some reason. I'll squashed your changes and submitted them as a single commit. Released as `0.7.0`

**Pull request closed without merging**
