### PR TITLE
Feature/find in set expression

### PR DESCRIPTION
**Pull request by hungthai1401**
Hi @tpetry ,
First, thanks for your package, it's very helpful for my working.
Sometime, I worked with [`FIND_IN_SET` operator in MySQL](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_find-in-set) so I want to contribute for this expression.
Plz take time to review it.

### CODE REVIEW

**Comment by tpetry** [comment]
Thanks for your contribution @hungthai1401. But it is not a good fit at the current implementation state.

The `FIND_IN_SET` function returns a match count for the search param. Only the MySQL implementation does that. So the meaning would have to be changed to something like `StrListContains`.

The SQLite implementation is incorrect for these cases:
* The match is the first element
* The match is the last element
* The match is the only element

**Comment by tpetry** [comment]
Btw you should use JSON columns instead as they don‘t have a problem with values containing `,` for the values. Its the much better approach.

**Comment by hungthai1401** [comment]
Thanks for your suggestion @tpetry . I add `strict` mode in this expression for solve case-insensitive and case-sensitive.
I understand that is good if use JSON columns but as you know, some legacy projects didn't use JSON in schema

**Comment by hungthai1401** [comment]
Hello @tpetry , are you here?

**Comment by tpetry** [comment]
I'll need some time to refactor your PR.

**Comment by tpetry** [comment]
I'll delay merging this PR until [laravel/framework#46558](https://github.com/laravel/framework/pull/46558) is merged. The current implementation of query expressions can't use arbitrary strings in expressions due to SQL injection problems. Only with the PR to Laravel this class will be of use.

**Comment by hungthai1401** [comment]
@tpetry I also follow your PR. Thank you for informing me

**Comment by hungthai1401** [comment]
@tpetry I can see that you PR has been merged

**Comment by tpetry** [comment]
Yes, but you'll have to wait for a Laravel release that includes the PR and a few days for me to include your PR. But it will be available soon ;)

**Comment by hungthai1401** [comment]
@tpetry I got it. thank you so much

**Comment by tpetry** [comment]
We'll have to wait another 2 weeks. My PR https://github.com/laravel/framework/pull/47210 was merged shortly after the Laravel 10.13 release. We need that release to do this:

```php
$query->where(new StringSetContains('type', new Value('blocked'))); 
```

I will polish your PR and prepare everything in the meantime. As soon as Laravel 10.14 is released I will then merge it.

**Comment by hungthai1401** [comment]
thanks for your info. I am very eager to use this syntax

**Comment by hungthai1401** [comment]
@tpetry Congratulation! Your PR has been released in v10.13.1

**Comment by hungthai1401** [comment]
@tpetry thanks for your great package.

**Pull request merged**
